### ISSUE TITLE
TypeError: Parameter "url" must be a string, not undefined

### ISSUE THREAD

**Issue by jsmithgmail** [stjohnjohnson/smartthings-mqtt-bridge#116]
I have installed mqtt via NPM, per the instructions.  When executing smartthings-mqtt-bridge, I receive the following response.  There doesnt appear to be a url parameter available to configure in the config.yml.  Configuration below.  I have tried both prefixing the IP address with mqtt and without, with the same results.  Any suggestions?  Running on raspberry pi 3.

`info: Starting SmartThings MQTT Bridge - v1.3.4
info: Loading configuration
info: Loading previous state
info: No previous state found, continuing
info: Perfoming configuration migration
url.js:103
    throw new TypeError('Parameter "url" must be a string, not ' + typeof url);
    ^

TypeError: Parameter "url" must be a string, not undefined
    at Url.parse (url.js:103:11)
    at Object.urlParse [as parse] (url.js:97:13)
    at migrateState (/usr/local/lib/node_modules/smartthings-mqtt-bridge/server.js:127:14)
    at loadFromDisk (/usr/local/lib/node_modules/smartthings-mqtt-bridge/server.js:302:9)
    at /usr/local/lib/node_modules/smartthings-mqtt-bridge/node_modules/async/lib/async.js:718:13
    at iterate (/usr/local/lib/node_modules/smartthings-mqtt-bridge/node_modules/async/lib/async.js:262:13)
    at async.forEachOfSeries.async.eachOfSeries (/usr/local/lib/node_modules/smartthings-mqtt-bridge/node_modules/async/lib/async.js:281:9)
    at _parallel (/usr/local/lib/node_modules/smartthings-mqtt-bridge/node_modules/async/lib/async.js:717:9)
    at Object.async.series (/usr/local/lib/node_modules/smartthings-mqtt-bridge/node_modules/async/lib/async.js:739:9)
    at Object.<anonymous> (/usr/local/lib/node_modules/smartthings-mqtt-bridge/server.js:287:7)`

`mqtt:
    # Specify your MQTT Broker's hostname or IP address here
host: mqtt://10.99.1.232
    # Preface for the topics $PREFACE/$DEVICE_NAME/$PROPERTY
preface: smartthings

    # Suffix for the state topics $PREFACE/$DEVICE_NAME/$PROPERTY/$STATE_SUFFIX
    # state_suffix: state
    # Suffix for the command topics $PREFACE/$DEVICE_NAME/$PROPERTY/$COMMAND_SUFFIX
    # command_suffix: cmd

    # Other optional settings from https://www.npmjs.com/package/mqtt#mqttclientstreambuilder-options
username: XXXXXX
password: XXXXXX

# Port number to listen on
port: 8080`

**Comment by stjohnjohnson** [comment]
That error means your host is not being read right.  Can you wrap the configuration in backticks to see the formatting.

**Comment by jsmithgmail** [comment]
Can you clarify what you mean by wrapping the configuration in backticks?  I know what a backtick is, but its not clear what I should wrap in backticks.  Do you mean change the config file for host for example to:

host: `mqtt://10.99.1.232`

**Comment by stjohnjohnson** [comment]
Looks like there is no indentation in your configuration.  That might be why.
