### ISSUE TITLE
ERROR: Input redirection is not supported, exiting the process immediately. execution expired (HTTPClient::ReceiveTimeoutError)

### ISSUE THREAD

**Issue by umapathireddy** [stjohnjohnson/smartthings-mqtt-bridge#186]

**Comment by umapathireddy** [comment]
20 : SuccessFactors Integration Center - Bonus Template.zip   : 201
21 : TryOutTestPackage.zip   : 201
  0.000000   0.015000   0.015000 (117.528378)
ERROR: Input redirection is not supported, exiting the process immediately.
ERROR: Input redirection is not supported, exiting the process immediately.
ERROR: Input redirection is not supported, exiting the process immediately.
ERROR: Input redirection is not supported, exiting the process immediately.
execution expired (HTTPClient::ReceiveTimeoutError)
D:/Ruby23/lib/ruby/gems/2.3.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:805:in `gets'
D:/Ruby23/lib/ruby/gems/2.3.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:805:in `block in parse_header'
D:/Ruby23/lib/ruby/2.3.0/timeout.rb:101:in `timeout'
